theme: jekyll-theme-minimal

title: JMetrics
description: JMetrics is a Java tool that measure software maintainability indicators through the Martin's Metric.
logo: jmetrics.png
show_downloads: "true"
